export const allNovels = [
	{
		id: 1,
		name: 'To Kill a Mockingbird',
		chapters: 20,
		likes: 100,
		category: 'Classic',
		author: 'Harper Lee',
	},
	{
		id: 2,
		name: '1984',
		chapters: 18,
		likes: 80,
		category: 'Dystopian',
		author: 'George Orwell',
	},
	{
		id: 3,
		name: 'Pride and Prejudice',
		chapters: 24,
		likes: 120,
		category: 'Romance',
		author: 'Jane Austen',
	},
	{
		id: 4,
		name: 'The Great Gatsby',
		chapters: 15,
		likes: 90,
		category: 'Classic',
		author: 'F. Scott Fitzgerald',
	},
	{
		id: 5,
		name: 'The Catcher in the Rye',
		chapters: 26,
		likes: 110,
		category: 'Coming-of-Age',
		author: 'J.D. Salinger',
	},
	{
		id: 6,
		name: 'Moby-Dick',
		chapters: 32,
		likes: 70,
		category: 'Adventure',
		author: 'Herman Melville',
	},
	{
		id: 7,
		name: 'War and Peace',
		chapters: 120,
		likes: 150,
		category: 'Historical Fiction',
		author: 'Leo Tolstoy',
	},
	{
		id: 8,
		name: 'The Lord of the Rings',
		chapters: 50,
		likes: 200,
		category: 'Fantasy',
		author: 'J.R.R. Tolkien',
	},
	{
		id: 9,
		name: 'To the Lighthouse',
		chapters: 15,
		likes: 60,
		category: 'Modernist',
		author: 'Virginia Woolf',
	},
	{
		id: 10,
		name: 'The Odyssey',
		chapters: 24,
		likes: 80,
		category: 'Epic',
		author: 'Homer',
	},
	{
		id: 11,
		name: 'Don Quixote',
		chapters: 60,
		likes: 130,
		category: 'Adventure',
		author: 'Miguel de Cervantes',
	},
	{
		id: 12,
		name: 'The Brothers Karamazov',
		chapters: 40,
		likes: 90,
		category: 'Classic',
		author: 'Fyodor Dostoevsky',
	},
	{
		id: 13,
		name: 'Frankenstein',
		chapters: 18,
		likes: 70,
		category: 'Gothic',
		author: 'Mary Shelley',
	},
	{
		id: 14,
		name: 'The Grapes of Wrath',
		chapters: 30,
		likes: 120,
		category: 'Social Commentary',
		author: 'John Steinbeck',
	},
	{
		id: 15,
		name: 'One Hundred Years of Solitude',
		chapters: 40,
		likes: 150,
		category: 'Magical Realism',
		author: 'Gabriel García Márquez',
	},
	{
		id: 16,
		name: 'Brave New World',
		chapters: 22,
		likes: 100,
		category: 'Dystopian',
		author: 'Aldous Huxley',
	},
	{
		id: 17,
		name: 'The Hobbit',
		chapters: 19,
		likes: 110,
		category: 'Fantasy',
		author: 'J.R.R. Tolkien',
	},
	{
		id: 18,
		name: 'The Alchemist',
		chapters: 20,
		likes: 140,
		category: 'Adventure',
		author: 'Paulo Coelho',
	},
	{
		id: 19,
		name: 'The Shining',
		chapters: 25,
		likes: 80,
		category: 'Horror',
		author: 'Stephen King',
	},
	{
		id: 20,
		name: "Alice's Adventures in Wonderland",
		chapters: 12,
		likes: 90,
		category: 'Fantasy',
		author: 'Lewis Carroll',
	},
	{
		id: 21,
		name: 'The Old Man and the Sea',
		chapters: 10,
		likes: 70,
		category: 'Adventure',
		author: 'Ernest Hemingway',
	},
	{
		id: 22,
		name: 'The Divine Comedy',
		chapters: 33,
		likes: 150,
		category: 'Epic',
		author: 'Dante Alighieri',
	},
	{
		id: 23,
		name: 'Les Misérables',
		chapters: 48,
		likes: 160,
		category: 'Historical Fiction',
		author: 'Victor Hugo',
	},
	{
		id: 24,
		name: 'Crime and Punishment',
		chapters: 30,
		likes: 110,
		category: 'Psychological Fiction',
		author: 'Fyodor Dostoevsky',
	},
	{
		id: 25,
		name: 'Gone with the Wind',
		chapters: 40,
		likes: 130,
		category: 'Historical Romance',
		author: 'Margaret Mitchell',
	},
	{
		id: 26,
		name: 'Lord of the Flies',
		chapters: 15,
		likes: 70,
		category: 'Adventure',
		author: 'William Golding',
	},
	{
		id: 27,
		name: 'The Picture of Dorian Gray',
		chapters: 20,
		likes: 80,
		category: 'Gothic',
		author: 'Oscar Wilde',
	},
	{
		id: 28,
		name: 'A Tale of Two Cities',
		chapters: 34,
		likes: 120,
		category: 'Historical Fiction',
		author: 'Charles Dickens',
	},
	{
		id: 29,
		name: 'Dracula',
		chapters: 29,
		likes: 100,
		category: 'Gothic',
		author: 'Bram Stoker',
	},
	{
		id: 30,
		name: 'The Scarlet Letter',
		chapters: 20,
		likes: 70,
		category: 'Romance',
		author: 'Nathaniel Hawthorne',
	},
	{
		id: 31,
		name: 'The Road',
		chapters: 16,
		likes: 60,
		category: 'Post-Apocalyptic',
		author: 'Cormac McCarthy',
	},
	{
		id: 32,
		name: 'The Sun Also Rises',
		chapters: 22,
		likes: 80,
		category: 'Lost Generation',
		author: 'Ernest Hemingway',
	},
	{
		id: 33,
		name: 'The Jungle',
		chapters: 30,
		likes: 90,
		category: 'Social Commentary',
		author: 'Upton Sinclair',
	},
	{
		id: 34,
		name: 'Fahrenheit 451',
		chapters: 18,
		likes: 100,
		category: 'Dystopian',
		author: 'Ray Bradbury',
	},
	{
		id: 35,
		name: "The Hitchhiker's Guide to the Galaxy",
		chapters: 20,
		likes: 110,
		category: 'Science Fiction',
		author: 'Douglas Adams',
	},
	{
		id: 36,
		name: 'The Princess Bride',
		chapters: 18,
		likes: 90,
		category: 'Fantasy',
		author: 'William Goldman',
	},
	{
		id: 37,
		name: 'The Secret Garden',
		chapters: 16,
		likes: 70,
		category: "Children's",
		author: 'Frances Hodgson Burnett',
	},
	{
		id: 38,
		name: 'Wuthering Heights',
		chapters: 22,
		likes: 80,
		category: 'Gothic',
		author: 'Emily Brontë',
	},
	{
		id: 39,
		name: "The Handmaid's Tale",
		chapters: 20,
		likes: 100,
		category: 'Dystopian',
		author: 'Margaret Atwood',
	},
	{
		id: 40,
		name: 'The Little Prince',
		chapters: 12,
		likes: 80,
		category: "Children's",
		author: 'Antoine de Saint-Exupéry',
	},
	{
		id: 41,
		name: 'The Road Not Taken',
		chapters: 1,
		likes: 40,
		category: 'Poetry',
		author: 'Robert Frost',
	},
	{
		id: 42,
		name: 'The Martian',
		chapters: 28,
		likes: 110,
		category: 'Science Fiction',
		author: 'Andy Weir',
	},
	{
		id: 43,
		name: 'The Hunger Games',
		chapters: 27,
		likes: 120,
		category: 'Dystopian',
		author: 'Suzanne Collins',
	},
	{
		id: 44,
		name: 'The Giver',
		chapters: 23,
		likes: 100,
		category: 'Dystopian',
		author: 'Lois Lowry',
	},
	{
		id: 45,
		name: 'The Outsiders',
		chapters: 12,
		likes: 70,
		category: 'Young Adult',
		author: 'S.E. Hinton',
	},
	{
		id: 46,
		name: 'The Chronicles of Narnia',
		chapters: 36,
		likes: 150,
		category: 'Fantasy',
		author: 'C.S. Lewis',
	},
	{
		id: 47,
		name: 'The Name of the Wind',
		chapters: 26,
		likes: 120,
		category: 'Fantasy',
		author: 'Patrick Rothfuss',
	},
	{
		id: 48,
		name: 'The Girl with the Dragon Tattoo',
		chapters: 30,
		likes: 110,
		category: 'Mystery',
		author: 'Stieg Larsson',
	},
	{
		id: 49,
		name: 'The Stand',
		chapters: 48,
		likes: 160,
		category: 'Horror',
		author: 'Stephen King',
	},
	{
		id: 50,
		name: 'The Wind in the Willows',
		chapters: 15,
		likes: 80,
		category: "Children's",
		author: 'Kenneth Grahame',
	},
];
