import Navbar from '@/components/Navbar';
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${poppins.className} bg-background selection:text-white selection:bg-primary selection:backdrop-blur-sm`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
